alert("This is simple alert box");
console.error("This is error message");
console.warn("This is warning message");
console.info("This is info message");
console.debug("This is debug message");

let roll=prompt("Enter your roll number");
console.log("Your roll number is "+roll);
msg="hello";
console.log(msg.trim().toUpperCase());
//push-add to end
//pop-delete from end and return it
//shift-add to start
//unshift-delete from start and return it